# Generated by Django 3.2.7 on 2021-09-30 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('otp_id', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_id', models.CharField(max_length=100, unique=True)),
                ('link', models.URLField()),
                ('otp_secret', models.CharField(max_length=100)),
                ('status', models.CharField(default='initiated', max_length=200)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('login', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getotp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
